In [1]:
"""1. Write a Python Program to Add Two Matrices?"""
import numpy
def add_matrices(l,m):
    n=numpy.matrix(l)
    m=numpy.matrix(m)
    return n+m
add_matrices([1,2,3,4],[4,3,2,1])

matrix([[5, 5, 5, 5]])

In [4]:
"""2. Write a Python Program to Multiply Two Matrices?"""
import numpy
def mul_matrices(l,m):
    n=numpy.matrix(l)
    m=numpy.matrix(m)
    return n*m
mul_matrices([1,2],[[21,2],[34,1]])

matrix([[89,  4]])

In [11]:
"""3. Write a Python Program to Transpose a Matrix?"""
import numpy
def trn_matrices(l):
    n=numpy.array(l)
    print(n)
    return n.transpose()
trn_matrices([[1,2,3],[21,2,4],[34,1,5]])

[[ 1  2  3]
 [21  2  4]
 [34  1  5]]


array([[ 1, 21, 34],
       [ 2,  2,  1],
       [ 3,  4,  5]])

In [19]:
"""4. Write a Python Program to Sort Words in Alphabetic Order?"""
def sortedWord(s):
    n=[i.upper() for i in s.split()]
    return sorted(n)
print(sortedWord("Hello this Is an Example With cased letters"))

['AN', 'CASED', 'EXAMPLE', 'HELLO', 'IS', 'LETTERS', 'THIS', 'WITH']


In [4]:
"""5. Write a Python Program to Remove Punctuation From a String?"""
def removePun(s):
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    word = ""
    for char in s:
        if char  in punctuations:
            pass
        else:
            word = word + char
    return word
removePun("Hello!!!, he said ---and went.")

'Hello he said and went'